version: '3'

services:
  payment-gateway:
    image: paymentgateway
    depends_on:
      - db
    ports:
      - 7777:80

  bank-service-a:
    image: bankservicea
    depends_on:
      - db
    ports:
      - 7778:80

  bank-service-b:
    image: bankserviceb
    depends_on:
      - db
    ports:
      - 7779:80

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sapass
    ports:
      - 8989:5432